Heat map
jdmartinez1062/Design-Teardown pull request #1
Opened 2019-09-06 22:34 UTC by jdmartinez1062

2019-09-07 01:42 UTC, Ispirett commented
# Revewing

2019-09-07 02:03 UTC, Ispirett requested changes
Hey @jdmartinez1062 @mariobarrioss    Excellent Job so far on this project you are doing a great job :100: 
![image](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png). 

See comment below 

submit for another review when finished

2019-09-07 02:03 UTC, Ispirett commented on index.HTML
> +        <footer class="heat-5">
Please add links layout you can use text, but this is for you to practice what you learnt before, you can use flex or floats.

2019-09-17 00:58 UTC, uche-inyama reviewed
## Pull request under review by: Inyama, Uchechukwu Henry

2019-09-17 01:12 UTC, uche-inyama requested changes
## Hi team :raised_hand_with_fingers_splayed: nice job.

 However, there are no Linter checks in this project.

- [ ] Ensure your project passes the checks, 

#### After affecting the change  :point_up_2:, submit another form for code review. :muscle: 

### This project hasn't been approved :stop_sign:

2019-09-23 17:53 UTC, whiz25 approved these changes
## Good to go :clap: 
Success in your next projects. Please merge and submit the completion form.
Use ```Afani Martin``` under TSE's who reviewed this project when submitting the project completion form.

2019-09-30 16:35 UTC, merged